version: '2'

services:
  db:
    build: db
    image: todo-app-db:latest
    command:
      - /bin/run_rqlite.sh
    ports:
      - 4001:4001

  api:
    build: api
    image: todo-app-api:latest
    command:
      - /webapp/run_api.sh
    depends_on:
      - db
    ports:
      - 5000:5000

  web:
    build: web
    image: todo-app-web:latest
    command:
      - /bin/run_web.sh
    depends_on:
      - api
    ports:
      - 3000:80
