meta:
  name: "Weather Stats App"
  description: "Application to get Weather, powered by Golem Network"
  author: "GolemFactory"
  version: "0.1.0"
payloads:
  cache:
    runtime: "vm"
    params:
      image_hash: "43ea70b47af16647473d1f9115be4deedd8dc3d3cf09e7a91807e2c9"
  api:
    runtime: "vm"
    params:
      image_hash: "6e1b1cf507a2636fcce61a67646697e5dd64d1c8907d042e8ba3863f"
  app:
    runtime: "vm"
    params:
      image_hash: "6f78afcbc7c76752cbc5366dda8ee1f3865aeccbe329f1c48fd00ec3"
nodes:
  cache:
    payload: "cache"
    init:
      - [
          "/bin/bash",
          "-c",
          "redis-server --bind 0.0.0.0 --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81 --loglevel debug > /dev/null &",
        ]
    http_proxy:
      ports:
        - "6379"
    network: "default"
    ip:
      - "192.168.0.2"
  api:
    payload: "api"
    init:
      - [
          "/bin/bash",
          "-c",
          "uvicorn weather.app:app --host 192.168.0.3 --port 5053 &",
        ]
    http_proxy:
      ports:
        - "5053"
    network: "default"
    ip:
      - "192.168.0.3"
  app:
    payload: "app"
    init:
      - ["/docker-entrypoint.sh"]
      - ["/bin/chmod", "a+x", "/"]
      - ["/usr/sbin/nginx"]
    http_proxy:
      ports:
        - "80"
    network: "default"
    ip:
      - "192.168.0.4"
networks:
  default:
    ip: "192.168.0.0/24"
