meta:
  name: "Weather Stats App"
  description: "Application to get Weather, powered by Golem Network"
  author: "GolemFactory"
  version: "0.1.0"
payloads:
  api:
    runtime: "vm"
    params:
      image_hash: "7d84979dd68fdeffd34f75de22c6e5ec3c9f62239d4048de8d9f46e3"
  app:
    runtime: "vm"
    params:
      image_hash: "c316c5b8869bbe93f568a55b5b5fabbbe79edf8a2405a24184b16abb"
nodes:
  api:
    payload: "api"
    init:
      - [
          "/bin/bash",
          "-c",
          "uvicorn weather.app:app --host 192.168.0.3 --port 5050 &",
        ]
    http_proxy:
      ports:
        - "5050"
    network: "default"
    ip:
      - "192.168.0.3"
  app:
    payload: "app"
    init:
      - ["/docker-entrypoint.sh"]
      - ["/bin/chmod", "a+x", "/"]
      - ["/usr/sbin/nginx"]
    http_proxy:
      ports:
        - "80"
    network: "default"
    ip:
      - "192.168.0.4"
networks:
  default:
    ip: "192.168.0.0/24"
