meta:
  name: "Weather Stats App"
  description: "Application to get Weather, powered by Golem Network"
  author: "GolemFactory"
  version: "0.1.0"
payloads:
  api:
    runtime: "vm"
    params:
      image_hash: "d431f9734bf3f398fafa029a18e42fa4feb2f348c5f58820d7604ef2"
  app:
    runtime: "vm"
    params:
      image_hash: "7de39d51bb766e65aa0ce2dd1221d7ddf25224eefe047cc576e31d16"
nodes:
  api:
    payload: "api"
    init:
      - ["/bin/bash", "-c", "uvicorn weather.app:app --host 192.168.0.3 --port 5050 &"]
    http_proxy:
      ports:
        - "5050"
    network: "default"
    ip:
      - "192.168.0.3"
  app:
    payload: "app"
    # init:
    #   - ["/bin/bash", "-c", "uvicorn weather.app:app --host 192.168.0.3 --port 5050 &"]
    http_proxy:
      ports:
        - "5060"
    network: "default"
    ip:
      - "192.168.0.4"
networks:
  default:
    ip: "192.168.0.0/24"
