meta:
  name: "Weather Stats App"
  description: "Application to get Weather, powered by Golem Network"
  author: "GolemFactory"
  version: "0.1.0"
payloads:
  cache:
    runtime: "vm"
    params:
      image_hash: "43ea70b47af16647473d1f9115be4deedd8dc3d3cf09e7a91807e2c9"
  api:
    runtime: "vm/manifest"
    params:
      capabilities:
        - inet
        - manifest-support
        - vpn
      manifest: ewogICAgInZlcnNpb24iOiAiMC4xLjAiLAogICAgImNyZWF0ZWRBdCI6ICIyMDIyLTA3LTI2VDEyOjUxOjAwLjAwMDAwMFoiLAogICAgImV4cGlyZXNBdCI6ICIyMTAwLTAxLTAxVDAwOjAxOjAwLjAwMDAwMFoiLAogICAgIm1ldGFkYXRhIjogewogICAgICAgICJuYW1lIjogIldlYXRoZXIgU3RhdHMgQXBwIiwKICAgICAgICAiZGVzY3JpcHRpb24iOiAiQXBwbGljYXRpb24gdG8gZ2V0IFdlYXRoZXIsIHBvd2VyZWQgYnkgR29sZW0gTmV0d29yayIsCiAgICAgICAgInZlcnNpb24iOiAiMC4xLjAiCiAgICB9LAogICAgInBheWxvYWQiOiBbCiAgICAgICAgewogICAgICAgICAgICAicGxhdGZvcm0iOiB7CiAgICAgICAgICAgICAgICAiYXJjaCI6ICJ4ODZfNjQiLAogICAgICAgICAgICAgICAgIm9zIjogImxpbnV4IgogICAgICAgICAgICB9LAogICAgICAgICAgICAidXJscyI6IFsKICAgICAgICAgICAgICAgICJodHRwOi8veWFjbjIuZGV2LmdvbGVtLm5ldHdvcms6ODAwMC9kb2NrZXItd2VhdGhlcl9zdGF0cy1hcGktbGF0ZXN0LTAyN2RmZDZmNTEuZ3ZtaSIKICAgICAgICAgICAgXSwKICAgICAgICAgICAgImhhc2giOiAic2hhMzo1MDU1MDlmY2U5OGJmYjkwNjcxMjUzMzRlNThhMzM0MDYxNWY4NjNhY2YyNThkNzI3NWNhMTI2NSIKICAgICAgICB9CiAgICBdLAogICAgImNvbXBNYW5pZmVzdCI6IHsKICAgICAgICAidmVyc2lvbiI6ICIwLjEuMCIsCiAgICAgICAgInNjcmlwdCI6IHsKICAgICAgICAgICAgImNvbW1hbmRzIjogWwogICAgICAgICAgICAgICAgInJ1biAuKnV2aWNvcm4uKiIKICAgICAgICAgICAgXSwKICAgICAgICAgICAgIm1hdGNoIjogInJlZ2V4IgogICAgICAgIH0sCiAgICAgICAgIm5ldCI6IHsKICAgICAgICAgICAgImluZXQiOiB7CiAgICAgICAgICAgICAgICAib3V0IjogewogICAgICAgICAgICAgICAgICAgICJwcm90b2NvbHMiOiBbCiAgICAgICAgICAgICAgICAgICAgICAgICJodHRwcyIsCiAgICAgICAgICAgICAgICAgICAgICAgICJodHRwIgogICAgICAgICAgICAgICAgICAgIF0sCiAgICAgICAgICAgICAgICAgICAgInVybHMiOiBbCiAgICAgICAgICAgICAgICAgICAgICAgICJodHRwOi8vYXBpLm9wZW53ZWF0aGVybWFwLm9yZyIKICAgICAgICAgICAgICAgICAgICBdCiAgICAgICAgICAgICAgICB9CiAgICAgICAgICAgIH0KICAgICAgICB9CiAgICB9Cn0=
      manifest_cert: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUIvekNDQVlXZ0F3SUJBZ0lVTCtzbFdPYUN5cEMwK1ZaTTk2Vk1XM2xOM1Jrd0NnWUlLb1pJemowRUF3SXcKT0RFV01CUUdBMVVFQ2d3TlIyOXNaVzBnUm1GamRHOXllVEVlTUJ3R0ExVUVBd3dWUjI5c1pXMGdSbUZqZEc5eQplU0JTVDA5VUlFTkJNQjRYRFRJeU1URXlNekV4TkRBMU0xb1hEVEkxTVRFeU1qRXhOREExTTFvd1FERVdNQlFHCkExVUVDZ3dOUjI5c1pXMGdSbUZqZEc5eWVURW1NQ1FHQTFVRUF3d2RSMjlzWlcwZ1JtRmpkRzl5ZVNCSlRsUkYKVWsxRlJFbEJWRVVnUTBFd1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DQUFTU0Z2cFFkOVEwaEUzMwpWY2RXWHg1N0JOWWZ4TDgySWVjaEFoY09GWk1mdXhsVUloM3NjSXJ2VnU3SUtLLzVXWkVlTXczU2xVN3pRckhmCnhEUWhXN0ZabzJVd1l6QU9CZ05WSFE4QkFmOEVCQU1DQVFZd0VnWURWUjBUQVFIL0JBZ3dCZ0VCL3dJQkFUQTkKQmdOVkhSOEJBZjhFTXpBeE1DK2dMYUFyaGlsb2RIUndjem92TDJOaExtZHZiR1Z0TG01bGRIZHZjbXN2WTNKcwpMMGRQVEVWTkxVTkJMbU55YkRBS0JnZ3Foa2pPUFFRREFnTm9BREJsQWpBTXo2aXlIcXVkd1kwV3dmT0dTRVd1ClF0SisveDBFenRNekhWS0ljMXNGck5GaEtUbTFyTm96bFgxazVkR2FNWjBDTVFEckNjQ0JzOVhpVkNqUklqc0cKVXFTand5WEpwclNBUW40ZzNrRk5PTENIcnpPby81SVM5TVpVSDBsbmVrYmFhMW89Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM3ekNDQXBXZ0F3SUJBZ0lVUURUbzc2QlRiZDFBZCtXaGo0Q3p3NVYvbXE4d0NnWUlLb1pJemowRUF3SXcKUURFV01CUUdBMVVFQ2d3TlIyOXNaVzBnUm1GamRHOXllVEVtTUNRR0ExVUVBd3dkUjI5c1pXMGdSbUZqZEc5eQplU0JKVGxSRlVrMUZSRWxCVkVVZ1EwRXdIaGNOTWpRd01qQXlNVE16TnpRMldoY05Nall3TVRFME1UTXpOelEyCldqQjZNUXN3Q1FZRFZRUUdFd0pCVlRFVE1CRUdBMVVFQ0F3S1UyOXRaUzFUZEdGMFpURVdNQlFHQTFVRUNnd04KUjI5c1pXMGdSbUZqZEc5eWVURVpNQmNHQTFVRUF3d1FaR0Z3Y0MxbGVIQmxjbWx0Wlc1MGN6RWpNQ0VHQ1NxRwpTSWIzRFFFSkFSWVVaR1YyYjNCelFHZHZiR1Z0TG01bGRIZHZjbXN3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBCkE0SUJEd0F3Z2dFS0FvSUJBUUN4SlFOczdONFQ3K2hKclB4ZlZReWw0cFFoQnpRcFpHQXJlQ0RGMVIwN0QzQ1gKdzE3NkNtQmFTQnZ2dTRCL3hEWmdKdnQ3WkphQ3Q5b3cxRVQ1MGZyNUR4SnRLcEpPQkJQRDZjUHRTUUNlcUFhZAoxWmR6aHd3ZHZxalpXQlRmcDVWOUpmWlJkVzM2akNOYkR3NkZkdElHM2JCUlljUWVSS0tvMFVEUTNwb01TTTlMCmdSaEIyQ1ZOUEo4c2xsMGY5TnRxODhZdnNsZnpDbGZlcUppMkhOblhHNFFnd08xL2xpZFo2S3RxTjF1MHpyOUoKd1FYbW52YW1NKzJRUHdCMlJjZnY5cjM4SG01blJlbG5hQ3BEUU50RVZQVkEzeXVwTHY2MXBkU1ZWSndvVVBCTQp3SzVJcDdac2U5ZWxnMVM2KzV4R2V5eEVzZVZ1eDBKejloWVhJOC9SQWdNQkFBR2phREJtTUEwR0ExVWREd0VCCi93UURBd0VBTUF3R0ExVWRFd0VCL3dRQ01BQXdSd1lEVlIwZkFRSC9CRDB3T3pBNW9EZWdOWVl6YUhSMGNITTYKTHk5allTNW5iMnhsYlM1dVpYUjNiM0pyTDJOeWJDOUhUMHhGVFMxSlRsUkZVazFGUkVsQlZFVXVZM0pzTUFvRwpDQ3FHU000OUJBTUNBMGdBTUVVQ0lCM0s2MG43dXZGOXp0cVhsb1hoVnVXYUgrRVhvWHdZcVUrZTQzQzAwTkhCCkFpRUE4M29RNHpLOTM5NXlqcTUzenZpZDhkME4rZmp4SEluaEVTd1lBQ0Q4Y1ZVPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
      manifest_sig: PD0oySgOvkUXqwyLS+PyMInUJ//e8I8FeLqtd4cjPbujBWGkGR1WNiyceCsrNXWp9xZB3T4TmyQBeQgFberxnNK67EwOz7Ik4WABCf2EtiRcg9CXL7M9KrhSMEOODWD7lG9HxhALAvKlrX6aiXpoEQEsVX1cIbrgt3y5yoYfRECqdCQIg7GMsQwhZyPNA1eDD+Zh/ZOAtNVDYKsT+FFiklx1EkBR0/ScjUyJwzM/Gpwt4bynmud6M3MY6L4hvWyeR4VgyGLohg1QBIlTpxnc98HCG1eDgRXlBik20NZCUdM9GqF1SQ03zS4RL86z3FC9naTCru8uxJpHQ9UNoFVXig==
      manifest_sig_algorithm: sha256
  app:
    runtime: "vm"
    params:
      image_hash: "5deb689ec435b6e4e64ef1af47706eee297ab67eeebbc26317d24253"
nodes:
  cache:
    payload: "cache"
    init:
      - ["/bin/bash", "-c", "redis-server --bind 0.0.0.0 --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81 --loglevel debug > /dev/null &"]
    network: "default"
    ip:
      - "192.168.0.2"
  api:
    payload: "api"
    init:
      - ["/bin/bash", "-c", "uvicorn weather.app:app --host 192.168.0.3 --port 5053 &"]
    network: "default"
    ip:
      - "192.168.0.3"
    depends_on:
      - "cache"
  app:
    payload: "app"
    init:
      - ["/docker-entrypoint.sh"]
      - ["/bin/chmod", "a+x", "/"]
      - ["/usr/sbin/nginx"]
    http_proxy:
      ports:
        - "80"
    network: "default"
    ip:
      - "192.168.0.4"
    depends_on:
      - "api"
networks:
  default:
    ip: "192.168.0.0/24"
