meta:
  name: "Weather Stats App"
  description: "Application to get Weather, powered by Golem Network"
  author: "GolemFactory"
  version: "0.1.0"
payloads:
  cache:
    runtime: "vm"
    params:
      image_hash: "43ea70b47af16647473d1f9115be4deedd8dc3d3cf09e7a91807e2c9"
  api:
    runtime: "vm/manifest"
    params:
      capabilities:
        - inet
        - manifest-support
        - vpn
      manifest: ewogICAgInZlcnNpb24iOiAiMC4xLjAiLAogICAgImNyZWF0ZWRBdCI6ICIyMDIyLTA3LTI2VDEyOjUxOjAwLjAwMDAwMFoiLAogICAgImV4cGlyZXNBdCI6ICIyMTAwLTAxLTAxVDAwOjAxOjAwLjAwMDAwMFoiLAogICAgIm1ldGFkYXRhIjogewogICAgICAgICJuYW1lIjogIldlYXRoZXIgU3RhdHMgQXBwIiwKICAgICAgICAiZGVzY3JpcHRpb24iOiAiQXBwbGljYXRpb24gdG8gZ2V0IFdlYXRoZXIsIHBvd2VyZWQgYnkgR29sZW0gTmV0d29yayIsCiAgICAgICAgInZlcnNpb24iOiAiMC4xLjAiCiAgICB9LAogICAgInBheWxvYWQiOiBbCiAgICAgICAgewogICAgICAgICAgICAicGxhdGZvcm0iOiB7CiAgICAgICAgICAgICAgICAiYXJjaCI6ICJ4ODZfNjQiLAogICAgICAgICAgICAgICAgIm9zIjogImxpbnV4IgogICAgICAgICAgICB9LAogICAgICAgICAgICAidXJscyI6IFsKICAgICAgICAgICAgICAgICJodHRwOi8veWFjbjIuZGV2LmdvbGVtLm5ldHdvcms6ODAwMC9kb2NrZXItd2VhdGhlcl9zdGF0cy1hcGktbGF0ZXN0LTAyN2RmZDZmNTEuZ3ZtaSIKICAgICAgICAgICAgXSwKICAgICAgICAgICAgImhhc2giOiAic2hhMzo1MDU1MDlmY2U5OGJmYjkwNjcxMjUzMzRlNThhMzM0MDYxNWY4NjNhY2YyNThkNzI3NWNhMTI2NSIKICAgICAgICB9CiAgICBdLAogICAgImNvbXBNYW5pZmVzdCI6IHsKICAgICAgICAidmVyc2lvbiI6ICIwLjEuMCIsCiAgICAgICAgInNjcmlwdCI6IHsKICAgICAgICAgICAgImNvbW1hbmRzIjogWwogICAgICAgICAgICAgICAgInJ1biAuKnV2aWNvcm4uKiIKICAgICAgICAgICAgXSwKICAgICAgICAgICAgIm1hdGNoIjogInJlZ2V4IgogICAgICAgIH0sCiAgICAgICAgIm5ldCI6IHsKICAgICAgICAgICAgImluZXQiOiB7CiAgICAgICAgICAgICAgICAib3V0IjogewogICAgICAgICAgICAgICAgICAgICJwcm90b2NvbHMiOiBbCiAgICAgICAgICAgICAgICAgICAgICAgICJodHRwcyIsCiAgICAgICAgICAgICAgICAgICAgICAgICJodHRwIgogICAgICAgICAgICAgICAgICAgIF0sCiAgICAgICAgICAgICAgICAgICAgInVybHMiOiBbCiAgICAgICAgICAgICAgICAgICAgICAgICJodHRwOi8vYXBpLm9wZW53ZWF0aGVybWFwLm9yZyIKICAgICAgICAgICAgICAgICAgICBdCiAgICAgICAgICAgICAgICB9CiAgICAgICAgICAgIH0KICAgICAgICB9CiAgICB9Cn0=
      # certificate used to sign the manifest will expire at 26.01.2023
      manifest_cert: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUIvekNDQVlXZ0F3SUJBZ0lVTCtzbFdPYUN5cEMwK1ZaTTk2Vk1XM2xOM1Jrd0NnWUlLb1pJemowRUF3SXcKT0RFV01CUUdBMVVFQ2d3TlIyOXNaVzBnUm1GamRHOXllVEVlTUJ3R0ExVUVBd3dWUjI5c1pXMGdSbUZqZEc5eQplU0JTVDA5VUlFTkJNQjRYRFRJeU1URXlNekV4TkRBMU0xb1hEVEkxTVRFeU1qRXhOREExTTFvd1FERVdNQlFHCkExVUVDZ3dOUjI5c1pXMGdSbUZqZEc5eWVURW1NQ1FHQTFVRUF3d2RSMjlzWlcwZ1JtRmpkRzl5ZVNCSlRsUkYKVWsxRlJFbEJWRVVnUTBFd1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DQUFTU0Z2cFFkOVEwaEUzMwpWY2RXWHg1N0JOWWZ4TDgySWVjaEFoY09GWk1mdXhsVUloM3NjSXJ2VnU3SUtLLzVXWkVlTXczU2xVN3pRckhmCnhEUWhXN0ZabzJVd1l6QU9CZ05WSFE4QkFmOEVCQU1DQVFZd0VnWURWUjBUQVFIL0JBZ3dCZ0VCL3dJQkFUQTkKQmdOVkhSOEJBZjhFTXpBeE1DK2dMYUFyaGlsb2RIUndjem92TDJOaExtZHZiR1Z0TG01bGRIZHZjbXN2WTNKcwpMMGRQVEVWTkxVTkJMbU55YkRBS0JnZ3Foa2pPUFFRREFnTm9BREJsQWpBTXo2aXlIcXVkd1kwV3dmT0dTRVd1ClF0SisveDBFenRNekhWS0ljMXNGck5GaEtUbTFyTm96bFgxazVkR2FNWjBDTVFEckNjQ0JzOVhpVkNqUklqc0cKVXFTand5WEpwclNBUW40ZzNrRk5PTENIcnpPby81SVM5TVpVSDBsbmVrYmFhMW89Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQXF5Z0F3SUJBZ0lVZUNyWWE0cEZ2VVZkVC81RWJzSHR3Lys1cVdZd0NnWUlLb1pJemowRUF3SXcKUURFV01CUUdBMVVFQ2d3TlIyOXNaVzBnUm1GamRHOXllVEVtTUNRR0ExVUVBd3dkUjI5c1pXMGdSbUZqZEc5eQplU0JKVGxSRlVrMUZSRWxCVkVVZ1EwRXdIaGNOTWpJeE1qSTNNVFl3TlRNMVdoY05Nak13TVRJMk1UWXdOVE0xCldqQ0JrREVMTUFrR0ExVUVCaE1DVUV3eEV6QVJCZ05WQkFnTUNsTnZiV1V0VTNSaGRHVXhFakFRQmdOVkJBY00KQ1V0eVlXdkRnOEt6ZHpFV01CUUdBMVVFQ2d3TlIyOXNaVzBnUm1GamRHOXllVEVWTUJNR0ExVUVBd3dNVEhWagphbUZ1SUVSMVpHVnJNU2t3SndZSktvWklodmNOQVFrQkZocHNkV05xWVc0dVpIVmtaV3RBWjI5c1pXMHVibVYwCmQyOXlhekNDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFJbmZaenNoY2c4TmlMQ3EKMmRLTC84RHgvWjBwWUNwSGRaWDE2MzVaM3d1bERQNEkwcGZrRkhDbll3cWZNN1ZkQlNZWS91OVNtRytZM3lNdApFdVFYSTA1WWoxMDV4cjhmR0FVSGo3V3VLNS92UGxaT0p0T2ZBRzNRZ3Vyc0pXa29NN2JPbHpEOFlqNVZoeHozCkZ1NUs0TTBGMmRMQkk3VFpRR0xlWUh1TjB6YXRCSW13ZXZGMUlrODlieWpUQTFlY2lNbUlIRm51andTamNYZ0sKdzU3NDJmYUt6RkNNSmozWTVMTStVb2I4R3VtODZsaHVCaXFXTzRDT3l0VitCeWZpRzhSeCtWY3F6YXlRQ05oVApIVE84bm1lbitPT1ZCZHhTRnhpNi9hRS9sMXE0d0tUcVFwSTBKQ01kRjJyMEpZR1ZORnRxNVZmWlZSSVdOZUg5CjhyejM1bDBDQXdFQUFhTm9NR1l3RFFZRFZSMFBBUUgvQkFNREFRQXdEQVlEVlIwVEFRSC9CQUl3QURCSEJnTlYKSFI4QkFmOEVQVEE3TURtZ042QTFoak5vZEhSd2N6b3ZMMk5oTG1kdmJHVnRMbTVsZEhkdmNtc3ZZM0pzTDBkUApURVZOTFVsT1ZFVlNUVVZFU1VGVVJTNWpjbXd3Q2dZSUtvWkl6ajBFQXdJRFJ3QXdSQUlnS2ZOT3BQMUhOMk80CkUvcUFCckM4MUhJOTFaeVNlS21iQkhqV0JIVXh2WnNDSUJqMHF0dlJDK3NIVmRYVUNLZE43NGlDWUh0cmIzSEQKQlZmUkR5dUExZEZXCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      manifest_sig: HQZGYp/+O7g8Z83t1FgC1M3CVT9Oap7DmKyRpPhpBwaXV073K6ayzQ7cpEiF22dVqE/plU2XDLzwlfkpzZVcl5TTrG7ioKiiHdRWuni1EIUKpmr/KAeUAn2xSPUlOkLtjpPvA1Zjt2mK8fWWu8/WyFMigwM0uiRg19BcvpvMoRv4Sc+OHOqyQ62+2lbviUB0PSjTxYIZRh0g4Ld+fRecWfDyXbkmqbmpyzGUQr2WRmpcga6P8VwSbiHKHvlqhrG29jyb6lnYdIoGmB0c7MqUYNgizH6rHbotxZEq/fxVN75kVBtGyFplUnQaUtVNG7EJFVmEPjHD9yZh0ra+h9ztTA==
      manifest_sig_algorithm: sha256
  app:
    runtime: "vm"
    params:
      image_hash: "8a82503b138a7600d937ad19e18136f26db10a7bcbed06bf20068ccf"
nodes:
  cache:
    payload: "cache"
    init:
      - [
          "/bin/bash",
          "-c",
          "redis-server --bind 0.0.0.0 --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81 --loglevel debug > /dev/null &",
        ]
    http_proxy:
      ports:
        - "6379"
    network: "default"
    ip:
      - "192.168.0.2"
  api:
    payload: "api"
    init:
      - [
          "/bin/bash",
          "-c",
          "uvicorn weather.app:app --host 192.168.0.3 --port 5053 &",
        ]
    http_proxy:
      ports:
        - "5053"
    network: "default"
    ip:
      - "192.168.0.3"
  app:
    payload: "app"
    init:
      - ["/docker-entrypoint.sh"]
      - ["/bin/chmod", "a+x", "/"]
      - ["/usr/sbin/nginx"]
    http_proxy:
      ports:
        - "80"
    network: "default"
    ip:
      - "192.168.0.4"
networks:
  default:
    ip: "192.168.0.0/24"
