meta:
  name: "Weather Stats App"
  description: "Application to get Weather, powered by Golem Network"
  author: "GolemFactory"
  version: "0.1.0"
payloads:
  cache:
    runtime: "vm"
    params:
      image_hash: "43ea70b47af16647473d1f9115be4deedd8dc3d3cf09e7a91807e2c9"
  api:
    runtime: "vm"
    params:
      image_hash: "a0858af8f2410c8a7a1ad95e578cc5fafcec64d7007e1cc992e4dc48"
  app:
    runtime: "vm"
    params:
      image_hash: "c316c5b8869bbe93f568a55b5b5fabbbe79edf8a2405a24184b16abb"
  playground:
    runtime: "vm"
    params:
      image_hash: "d856e8c4493bfa153ff7ff186887073b2b5dacd651fc43c2df826568"
nodes:
  cache:
    payload: "cache"
    init:
      - ["/bin/bash", "-c", "redis-server --bind 0.0.0.0 --loglevel debug > /dev/null &"]
    http_proxy:
      ports:
        - "6379"
    network: "default"
    ip:
      - "192.168.0.1"
  api:
    payload: "api"
    init:
      - ["/bin/bash", "-c", "uvicorn weather.app:app --host 192.168.0.2 --port 5052 &",]
    http_proxy:
      ports:
        - "5052"
    network: "default"
    ip:
      - "192.168.0.2"
  app:
    payload: "app"
    init:
      - ["/docker-entrypoint.sh"]
      - ["/bin/chmod", "a+x", "/"]
      - ["/usr/sbin/nginx"]
    http_proxy:
      ports:
        - "80"
    network: "default"
    ip:
      - "192.168.0.3"
  playground:
    payload: "playground"
    init:
      - ["/bin/bash", "-c", "redis-server --bind 0.0.0.0 --loglevel debug > /dev/null &"]
      - ["/bin/bash", "-c", "uvicorn playground.app:app --host 192.168.0.4 --port 5054 &"]
    http_proxy:
      ports:
        - "5054"
    network: "default"
    ip:
      - "192.168.0.4"
networks:
  default:
    ip: "192.168.0.0/24"
