meta:
  name: "Weather Stats App"
  description: "Application to get Weather, powered by Golem Network"
  author: "GolemFactory"
  version: "0.1.0"
payloads:
  cache:
    runtime: "vm"
    params:
      image_hash: "43ea70b47af16647473d1f9115be4deedd8dc3d3cf09e7a91807e2c9"
  api:
    runtime: "vm"
    params:
      image_hash: "a5ffd7617161bcabff57cd668c95fd3366a19fe3556a5a7e9dd77003"
  app:
    runtime: "vm"
    params:
      image_hash: "6f78afcbc7c76752cbc5366dda8ee1f3865aeccbe329f1c48fd00ec3"
  playground:
    runtime: "vm"
    params:
      image_hash: "d856e8c4493bfa153ff7ff186887073b2b5dacd651fc43c2df826568"
nodes:
  cache:
    payload: "cache"
    init:
      - ["/bin/bash", "-c", "redis-server --bind 0.0.0.0 --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81 --loglevel debug > /dev/null &"]
    http_proxy:
      ports:
        - "6379"
    network: "default"
    ip:
      - "192.168.0.2"
  api:
    payload: "api"
    init:
      - ["/bin/bash", "-c", "uvicorn weather.app:app --host 192.168.0.3 --port 5053 &",]
    http_proxy:
      ports:
        - "5053"
    network: "default"
    ip:
      - "192.168.0.3"
  app:
    payload: "app"
    init:
      - ["/docker-entrypoint.sh"]
      - ["/bin/chmod", "a+x", "/"]
      - ["/usr/sbin/nginx"]
    http_proxy:
      ports:
        - "80"
    network: "default"
    ip:
      - "192.168.0.4"
networks:
  default:
    ip: "192.168.0.0/24"
