meta:
  name: "Weather Stats App"
  description: "Application to get Weather, powered by Golem Network"
  author: "GolemFactory"
  version: "0.1.0"
payloads:
  cache:
    runtime: "vm"
    params:
      image_hash: "43ea70b47af16647473d1f9115be4deedd8dc3d3cf09e7a91807e2c9"
  api:
    runtime: "vm/manifest"
    params:
      capabilities:
        - inet
        - manifest-support
        - vpn
      manifest: ewogICAgInZlcnNpb24iOiAiMC4xLjAiLAogICAgImNyZWF0ZWRBdCI6ICIyMDIyLTA3LTI2VDEyOjUxOjAwLjAwMDAwMFoiLAogICAgImV4cGlyZXNBdCI6ICIyMTAwLTAxLTAxVDAwOjAxOjAwLjAwMDAwMFoiLAogICAgIm1ldGFkYXRhIjogewogICAgICAgICJuYW1lIjogIldlYXRoZXIgU3RhdHMgQXBwIiwKICAgICAgICAiZGVzY3JpcHRpb24iOiAiQXBwbGljYXRpb24gdG8gZ2V0IFdlYXRoZXIsIHBvd2VyZWQgYnkgR29sZW0gTmV0d29yayIsCiAgICAgICAgInZlcnNpb24iOiAiMC4xLjAiCiAgICB9LAogICAgInBheWxvYWQiOiBbCiAgICAgICAgewogICAgICAgICAgICAicGxhdGZvcm0iOiB7CiAgICAgICAgICAgICAgICAiYXJjaCI6ICJ4ODZfNjQiLAogICAgICAgICAgICAgICAgIm9zIjogImxpbnV4IgogICAgICAgICAgICB9LAogICAgICAgICAgICAidXJscyI6IFsKICAgICAgICAgICAgICAgICJodHRwOi8veWFjbjIuZGV2LmdvbGVtLm5ldHdvcms6ODAwMC9kb2NrZXItd2VhdGhlcl9zdGF0cy1hcGktbGF0ZXN0LTAyN2RmZDZmNTEuZ3ZtaSIKICAgICAgICAgICAgXSwKICAgICAgICAgICAgImhhc2giOiAic2hhMzo1MDU1MDlmY2U5OGJmYjkwNjcxMjUzMzRlNThhMzM0MDYxNWY4NjNhY2YyNThkNzI3NWNhMTI2NSIKICAgICAgICB9CiAgICBdLAogICAgImNvbXBNYW5pZmVzdCI6IHsKICAgICAgICAidmVyc2lvbiI6ICIwLjEuMCIsCiAgICAgICAgInNjcmlwdCI6IHsKICAgICAgICAgICAgImNvbW1hbmRzIjogWwogICAgICAgICAgICAgICAgInJ1biAuKnV2aWNvcm4uKiIKICAgICAgICAgICAgXSwKICAgICAgICAgICAgIm1hdGNoIjogInJlZ2V4IgogICAgICAgIH0sCiAgICAgICAgIm5ldCI6IHsKICAgICAgICAgICAgImluZXQiOiB7CiAgICAgICAgICAgICAgICAib3V0IjogewogICAgICAgICAgICAgICAgICAgICJwcm90b2NvbHMiOiBbCiAgICAgICAgICAgICAgICAgICAgICAgICJodHRwcyIsCiAgICAgICAgICAgICAgICAgICAgICAgICJodHRwIgogICAgICAgICAgICAgICAgICAgIF0sCiAgICAgICAgICAgICAgICAgICAgInVybHMiOiBbCiAgICAgICAgICAgICAgICAgICAgICAgICJodHRwOi8vYXBpLm9wZW53ZWF0aGVybWFwLm9yZyIKICAgICAgICAgICAgICAgICAgICBdCiAgICAgICAgICAgICAgICB9CiAgICAgICAgICAgIH0KICAgICAgICB9CiAgICB9Cn0=
      # certificate used to sign the manifest will expire at 10.05.2023
      manifest_cert: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUIvekNDQVlXZ0F3SUJBZ0lVTCtzbFdPYUN5cEMwK1ZaTTk2Vk1XM2xOM1Jrd0NnWUlLb1pJemowRUF3SXcKT0RFV01CUUdBMVVFQ2d3TlIyOXNaVzBnUm1GamRHOXllVEVlTUJ3R0ExVUVBd3dWUjI5c1pXMGdSbUZqZEc5eQplU0JTVDA5VUlFTkJNQjRYRFRJeU1URXlNekV4TkRBMU0xb1hEVEkxTVRFeU1qRXhOREExTTFvd1FERVdNQlFHCkExVUVDZ3dOUjI5c1pXMGdSbUZqZEc5eWVURW1NQ1FHQTFVRUF3d2RSMjlzWlcwZ1JtRmpkRzl5ZVNCSlRsUkYKVWsxRlJFbEJWRVVnUTBFd1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DQUFTU0Z2cFFkOVEwaEUzMwpWY2RXWHg1N0JOWWZ4TDgySWVjaEFoY09GWk1mdXhsVUloM3NjSXJ2VnU3SUtLLzVXWkVlTXczU2xVN3pRckhmCnhEUWhXN0ZabzJVd1l6QU9CZ05WSFE4QkFmOEVCQU1DQVFZd0VnWURWUjBUQVFIL0JBZ3dCZ0VCL3dJQkFUQTkKQmdOVkhSOEJBZjhFTXpBeE1DK2dMYUFyaGlsb2RIUndjem92TDJOaExtZHZiR1Z0TG01bGRIZHZjbXN2WTNKcwpMMGRQVEVWTkxVTkJMbU55YkRBS0JnZ3Foa2pPUFFRREFnTm9BREJsQWpBTXo2aXlIcXVkd1kwV3dmT0dTRVd1ClF0SisveDBFenRNekhWS0ljMXNGck5GaEtUbTFyTm96bFgxazVkR2FNWjBDTVFEckNjQ0JzOVhpVkNqUklqc0cKVXFTand5WEpwclNBUW40ZzNrRk5PTENIcnpPby81SVM5TVpVSDBsbmVrYmFhMW89Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMyRENDQW4rZ0F3SUJBZ0lVR1k4RU5DcGlmaDF1SVdGK3UzUk43Qzk4M0JJd0NnWUlLb1pJemowRUF3SXcKUURFV01CUUdBMVVFQ2d3TlIyOXNaVzBnUm1GamRHOXllVEVtTUNRR0ExVUVBd3dkUjI5c1pXMGdSbUZqZEc5eQplU0JKVGxSRlVrMUZSRWxCVkVVZ1EwRXdIaGNOTWpNd01qQTVNVEV6TURNd1doY05Nak13TlRFd01URXpNRE13CldqQmRNUnd3R2dZRFZRUUtEQk5IYjJ4bGJTQlRhRzkzWTJGelpTQlVaV0Z0TVJZd0ZBWURWUVFEREExVGFHOTMKWTJGelpTQlVaV0ZyTVNVd0l3WUpLb1pJaHZjTkFRa0JGaFpuY25wbFoyOXlla0JuYjJ4bGJTNXVaWFIzYjNKcgpNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXdlVlpjL2gzYnBtUWVrK0IwdkZ1CjhxUjd0RzlFRVRrL3RzQzhLdHpBeEV0aDhPMU5jMVZPZ29JTXY0eGMzOFVWdC8rZkpobnlVUng5dzNhTWJ1MzUKR1ExVE1UU0FXM2NMOGpjN1kzZ0ZMVkFCdDltQVdkam1XeU9UeEZKdGkrNjhYdlBBMExhaUFJem9Kc2t5ZThuVwpUZkZXeXM5SzVlekZRZVRPWSs2eCtWNXFGRjZKQ0dlOVo3bGV0UnIzelRrdWZacFZ1TERDSHNNU0RZSlBWd3FHCk1kQ1haa1Q1bis4dWZERmtTSUFmaUdGY2kvbFFpbVFUVjd0Y2tQUXlqdXZhSUplU3NrYkJhVDM5dGRRS25aMHUKeTVtVW52cWFLU0c2SXZMTlF3Z3ZYdSt3bG1xYWFhVW02VDZ1bmYyTHY5TGVuaXhQUk5tL3lUSTJnZUU3WitBQQpId0lEQVFBQm8yOHdiVEFPQmdOVkhROEJBZjhFQkFNQ0FZWXdFZ1lEVlIwVEFRSC9CQWd3QmdFQi93SUJBVEJICkJnTlZIUjhCQWY4RVBUQTdNRG1nTjZBMWhqTm9kSFJ3Y3pvdkwyTmhMbWR2YkdWdExtNWxkSGR2Y21zdlkzSnMKTDBkUFRFVk5MVWxPVkVWU1RVVkVTVUZVUlM1amNtd3dDZ1lJS29aSXpqMEVBd0lEUndBd1JBSWdHM3JtN21SawpRZTZ1QzZRSnFUR0sydU43azV0WFdCdEdYb2FwUlgvNHJId0NJSDNRU2RWRGJMMTYyTlRSdXpZOUttelpUOWg4CjJBWDBCU0dBWktzYUdnaTcKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
      manifest_sig: H8WR7eGEuuAVynEk/NJqsyfUrQuR+asaAcHCiDJvpB75aD80t4N3QjVitENp7D0++oDfmfX+KhLY0QIqMbCTrmkw1VcybzshSr9s8uem7fPXZzo8vRJshGfTF9de9JB6MkgFHbX547X9Ub9taErHPLbUUvQ21XMnOC9hNyOQjpw9gMecKT8+5aGXrye/EBdQjh0QofHC3BRLInTXkU7k949E7mtOxs0tWG8O2JUM7J68KhGJEO94jHOVPUt+zR8NMT6/RFotZKj0GZywF6H7Fx7x+4ESw+xBeZdwrbaWLYD5uDuRt35cRipMszEQJhfg7vwnCrlKk0WwkaOffmroQA==
      manifest_sig_algorithm: sha256
  app:
    runtime: "vm"
    params:
      image_hash: "9098830d7d141d80ab76ee9f76a936fe358400554cf3b7254985dbe7"
nodes:
  cache:
    payload: "cache"
    init:
      - [
          "/bin/bash",
          "-c",
          "redis-server --bind 0.0.0.0 --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81 --loglevel debug > /dev/null &",
        ]
    http_proxy:
      ports:
        - "6379"
    network: "default"
    ip:
      - "192.168.0.2"
  api:
    payload: "api"
    init:
      - [
          "/bin/bash",
          "-c",
          "uvicorn weather.app:app --host 192.168.0.3 --port 5053 &",
        ]
    http_proxy:
      ports:
        - "5053"
    network: "default"
    ip:
      - "192.168.0.3"
  app:
    payload: "app"
    init:
      - ["/docker-entrypoint.sh"]
      - ["/bin/chmod", "a+x", "/"]
      - ["/usr/sbin/nginx"]
    http_proxy:
      ports:
        - "80"
    network: "default"
    ip:
      - "192.168.0.4"
networks:
  default:
    ip: "192.168.0.0/24"
