meta:
    name: "GLM Query"
    author: "Golem Factory"
    description: "A minimal app querying the GLM smart contract for the current balance."
    version: "0.1.0"
payloads:
    backend:
        runtime: "vm/manifest"
        params:
            manifest: ewogICAgInZlcnNpb24iOiAiMC4xLjAiLAogICAgImNyZWF0ZWRBdCI6ICIyMDIyLTEyLTAxVDAwOjAwOjAwLjAwMDAwMFoiLAogICAgImV4cGlyZXNBdCI6ICIyMTAwLTAxLTAxVDAwOjAwOjAwLjAwMDAwMFoiLAogICAgInBheWxvYWQiOiBbCiAgICAgICAgewogICAgICAgICAgInBsYXRmb3JtIjogewogICAgICAgICAgICAiYXJjaCI6ICJ4ODZfNjQiLAogICAgICAgICAgICAib3MiOiAibGludXgiCiAgICAgICAgICB9LAogICAgICAgICAgInVybHMiOiBbCiAgICAgICAgICAgICJodHRwOi8vZ2lyZXBvLmRldi5nb2xlbS5uZXR3b3JrOjgwMDAvZG9ja2VyLWdsbV9xdWVyeS1sYXRlc3QtNzAxNWU1YmQxYi5ndm1pIgogICAgICAgICAgXSwKICAgICAgICAgICJoYXNoIjogInNoYTM6MDNkMDNlZTAzMDNkZDhkOTUzNjRlYmU0MmFmYjJmMjg5NTViNDQ4Njc2NGJjOGUyNzE0Yzk1M2UiCiAgICAgICAgfQogICAgICBdLAogICAgICAiY29tcE1hbmlmZXN0IjogewogICAgICAidmVyc2lvbiI6ICIwLjEuMCIsCiAgICAgICJzY3JpcHQiOiB7CiAgICAgICAgImNvbW1hbmRzIjogWwogICAgICAgICAgInJ1biAuKiIKICAgICAgICBdLAogICAgICAgICJtYXRjaCI6ICJyZWdleCIKICAgICAgfSwKICAgICAgIm5ldCI6IHsKICAgICAgICAiaW5ldCI6IHsKICAgICAgICAgICJvdXQiOiB7CiAgICAgICAgICAgICJwcm90b2NvbHMiOiBbCiAgICAgICAgICAgICAgImh0dHAiCiAgICAgICAgICAgIF0sCiAgICAgICAgICAgICJ1cmxzIjogWwogICAgICAgICAgICAgICAgImh0dHA6Ly9ib3IuZ29sZW0ubmV0d29yayIsCiAgICAgICAgICAgICAgICAiaHR0cHM6Ly9nZXRoLmdvbGVtLm5ldHdvcms6NTU1NTUiLAogICAgICAgICAgICAgICAgImh0dHBzOi8vYm9yLmdvbGVtLm5ldHdvcmsiLAogICAgICAgICAgICAgICAgImh0dHA6Ly9nZXRoLnRlc3RuZXQuZ29sZW0ubmV0d29yazo1NTU1NSIKICAgICAgICAgICAgXQogICAgICAgICAgfQogICAgICAgIH0KICAgICAgfQogICAgfQogIH0=
    frontend:
        runtime: "vm"
        params:
            image_hash: "d8ce32bb8e388763d0157b581fbf432d24596386b87111453e58b3c3"

nodes:
    backend:
        payload: "backend"
        init:
            - run:
                  args: ["/bin/sh", "-c", "poetry run glm_query run > out 2> err &"]
        network: "default"
        http_proxy:
            ports:
                - "9000:9000"
        ip:
            - "192.168.1.3"
    frontend:
        payload: "frontend"
        network: "default"
        depends_on:
            - "backend"
        http_proxy:
            ports:
                - "80:80"
        init:
            - ["/docker-entrypoint.sh"]
            - ["/bin/chmod", "a+x", "/"]
            - ["/usr/sbin/nginx"]
        ip:
            - "192.168.1.4"
networks:
    default:
        ip: "192.168.1.0/24"
